### ISSUE TITLE
Request for angular code

### ISSUE THREAD

**Issue by RenjiEapen** [bpmn-io/bpmn-js-example-custom-shapes#2]
Is angular code available for this?

**Comment by pinussilvestrus** [comment]
Can you explain what you want to achieve? This example doesn't depend on any js framework. You can refer to the [angular example](https://github.com/bpmn-io/bpmn-js-example-angular) how to integrate bpmn-js into an angular application. This way you can also implement your custom shapes as this example explains.

**Comment by RenjiEapen** [comment]
I am using https://github.com/narve/angular-bpmn and currently working. I want to add a new shape to it. How can I use BPMN-js-example-custom-shapes for that?

**Comment by philippfromme** [comment]
For questions please head over to our dedicated [forum](https://forum.bpmn.io/). GitHub issues are better suited for bugs and feature requests.
