### ISSUE TITLE
Broken link for custom modeling example

### ISSUE THREAD

**Issue by ScarletFlash** [bpmn-io/bpmn-js-example-custom-shapes#3]
The link to custom modeler example is broken: https://github.com/bpmn-io/bpmn-js-example-custom-shapes/blob/master/README.md#usage-summary

https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-elements/app/custom-modeler/index.js

**Comment by pinussilvestrus** [comment]
Thanks for reporting! I updated the links accordingly.
