### ISSUE TITLE
how do i add properties to custom shapes?

### ISSUE THREAD

**Issue by vdeppe** [bpmn-io/bpmn-js-example-custom-shapes#4]
Hello,
according to the custom shapes example: How can I add properties to these shapes?
I already tried similar to the custom Elements example via a json file, but that doesn't
work for the shape example.
Thanks in Advance and Kind regards

**Comment by philippfromme** [comment]
Are you sure that entirely new shapes are the right approach for you? Please follow the customization guide first: https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements

**Comment by vdeppe** [comment]
When I add a new font as described here: https://github.com/bpmn-io/bpmn-font/blob/master/docs/HOWTO.md  , do I get a new bpmn-element then, which will be rendered as described in the font and for that I can add new properties?

**Comment by nikku** [comment]
Please answer @philippfromme's question.

What would you like to achieve? What did you try? What did not work?

**Comment by vdeppe** [comment]
I tried to add an entirely new bpmn-element and first I orientied myself on the custom-shapes example. But with this it seems not possible to add properties to the custom-shapes. In the Moment I try it via extending bpmn:Transaction, since this element Comes closely to what I need. Adding new properties to it seems to work as well, but I can't figure out how to override its rendering. The Rendering should look exactly as its css-picture but with enough space between the 2 rectangles, such that text can be within and without the + Symbol.

**Comment by vdeppe** [comment]
in addition: for the new properties I created the following json-file and added it to the modeller via moddleExtensions: {
    app: ModelExtension
  }

{
  "name": "AppID",
  "prefix": "app",
  "uri": "http://appID",
  "xml": {
    "tagAlias": "lowerCase"
  },
  "associations": [],
  "types": [
    {
      "name": "Assistance_System",
	   "superClass": [
        "bpmn:Artifact"
      ],
	  "extends": [
        "bpmn:Transaction"
      ],
      "properties": [
        {
			"name": "ApplicationID",
			"isAttr": true,
			"type": "Integer"
        },
		{
			"name": "AssistanceSystemType",
			"isAttr": true,
			"type": "String"
		}
      ]
    }
  ]
}

the lines:
 "superClass": [
        "bpmn:Artifact"
      ]
shall cause the bpmn:Transaction to inherit the properties, which bpmn:Artifact already has.
Is this the right way to add and inherit properties?

**Comment by pinussilvestrus** [comment]
First, please make sure to [format your code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code), it's hard to read otherwise.

But to answer your question, yes, using `superClass` is the intended way to inherit properties.

> but I can't figure out how to override its rendering

What does not work there? Did you [check the custom rendering example](https://github.com/bpmn-io/bpmn-js-example-custom-rendering)?

**Comment by vdeppe** [comment]
Thanks for your answer. I now checked the rendering example, but I do not understand for what the getShapePath-method is good for. When I comment out that method, the custom rectangle is drawn as well. Please explain what the method does exactly.

**Comment by pinussilvestrus** [comment]
Sorry for not responding. If you have questions it's better to [ask them in the forum](https://forum.bpmn.io/). GitHub issues are better for feature requests and bug reports
